tasks:
  - command: /opt/bin/entry_point.sh & /opt/novnc/utils/launch.sh --vnc "localhost:5900" --listen "6080" &
  - command: npm i && npm run compile -- -w & echo -e "\n\nYou are ready! \nRun your test by 'npm run test'\n"

image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - LogiGear.gondola-studio@1.6.214:t/ZCYrWASrUbYRH/pKXG/g==
